ccflags-y += -Idrivers/media/platform/msm/camera_v2_e5
ccflags-y += -Idrivers/media/platform/msm/camera_v2_e5/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_e5/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
